/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Encryption */

#ifndef _Included_Encryption
#define _Included_Encryption
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Encryption
 * Method:    encrypt
 * Signature: ([B[B)[I
 */
JNIEXPORT jintArray JNICALL Java_Encryption_encrypt
  (JNIEnv *, jobject, jbyteArray, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
